make an appointment
Andres-UA/automation-challenge pull request #2
Opened 2019-10-11 16:15 UTC by Andres-UA

2019-10-11 19:34 UTC, holgiosalos requested changes
This is a really good approach. However, I would have liked to see API consumption, for example, to add patient or doctors. (This is not required and is not needed for you add any additional change to the ones on this review)

2019-10-11 19:34 UTC, holgiosalos commented on src/page/confirmation-page.ts
> +
unneded blank line

2019-10-11 19:34 UTC, holgiosalos commented on test/make-appointment.spec.ts
> +    await browser.get('http://automatizacion.herokuapp.com/aurbano/');
make the URL constant

2019-10-11 19:34 UTC, holgiosalos commented on test/make-appointment.spec.ts
> +describe('Make an appointment', () => {
It is better if you follow gherking. For example:
Given I want to schedule a meddical appointment (describe on line 11)
and doctor exists in system (it on line 21)
and I create my patient user (it on line 29)
when I schedule the appointment on <Date> 
then I should get a confirmation message 

for the last two steps you should split the **it** function on line 37

2019-10-12 21:15 UTC, yesid-lopez approved these changes
Great work!

2019-10-15 20:37 UTC, holgiosalos approved these changes
Very interesting approach and great work!

2019-10-15 20:38 UTC, merged